### ISSUE TITLE
"jsonBody" parameter type in taskForPOSTMethod header in TMDBClient.swift file

### ISSUE THREAD

**Issue by ivdekov** [udacity/ios-nd-networking#1]
Hey Jarrod,

Your lessons on networking with Swift are great! I am not only learning a lot but I am enjoying them as well.

I wanted to bring something small to your attention. 

In the following file: ios-nd-networking/TheMovieManager-v1/TheMovieManager/TMDBClient.swift

There is the following unimplemented method:

`taskForPOSTMethod(method: String, var parameters: [String:AnyObject], jsonBody: [String:AnyObject], completionHandlerForPOST: (result: AnyObject!, error: NSError?) -> Void) -> NSURLSessionDataTask {}`

In this method header, the type of the jsonBody parameter is `[String:AnyObject]`. However, in the same method header of the other two TheMovieManager projects (located in the TheMovieManager-v2 and TheMovieManagerComplete folders), the jsonBody parameter is of type`String`.

**Comment by OwenLaRosa** [comment]
Closing this out as there's a new version of the course.
